//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 01:45:54 PM EET 
//


package com.ua.training;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="constellation" type="{http://techprimers.com/spring-boot-soap-example}user"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "constellation"
})
@XmlRootElement(name = "postUserRequest")
public class PostUserRequest {

    @XmlElement(required = true)
    protected User constellation;

    /**
     * Gets the value of the constellation property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getConstellation() {
        return constellation;
    }

    /**
     * Sets the value of the constellation property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setConstellation(User value) {
        this.constellation = value;
    }

}
